var languages = {
    eng : {
        "language": "English",
        "lang": "eng",
        "string welcome page": "Welcome to our ship",
        "button login": "Login",
        "button logout": "Logout",
        "string swipe up": "Swipe up if you don't have an account",
        "string sign in": "Sign in",
        "label email id": "Email id",
        "placeholder email": "me@email.com",
        "label password": "Password",
        "button back": "Back",
        "pop up login out": "You have been logged out succesfully",
        "string table": "table",
        "string balance": "balance",
        "string special VIP section": "Specials for You",
        "placeholder search bar": "search",
        "placeholder categories filter": "All Categories",
        "placeholder allergies": "Allergies",
        "string order menu": "Order",
        "string new customer": "customer",
        "string multiple customers": "Multiple Customers",
        "string total order": "Total",
        "string account balance order": "Account balance",
        "string balance after order": "New balance",
        "button info" : "i",
        "button fridge code": "Code",
        "button fridge code explanation": "hold to view",
        "pop up order sent": "The order has been sent to our bartender",
        "string drag order": "CstmrDrag item here to order",
        "message customer name": "Please input your name:",
        "navigation order": "ORDER",
        "navigation inventory": "INVENTORY",
        "button single order": "Single Order",
        "button modify order": "Modify Order",
        "button finished modify": "Finished Modifying",
        "button add from menu": "Add From Menu",
        "button duplicate": "Duplicate",
        "button discount": "Discount",
        "button free": "Free",
        "button remove": "Remove",
        "string unassigned": "Unassigned",
        "string add customer allcaps": "ADD CUSTOMER",
        "string remove customer allcaps": "REMOVE CUSTOMER"
    },

    fra : {
        "language": "Français",
        "lang": "fra",
        "string welcome page": "Bienvenu à bord",
        "button login": "Se connecter",
        "button logout": "Se déconnecter",
        "string swipe up": "Swipe up si vous n'avez pas de compte",
        "string sign in": "S'inscrire",
        "label email id": "Email",
        "placeholder email": "me@email.com",
        "label password": "Mot de pass",
        "button back": "Retour",
        "pop up login out": "Vous avez été déconecté",
        "string table": "table",
        "string balance": "solde",
        "string special VIP section": "Spécials pour vous",
        "placeholder search bar": "Rechercher",
        "placeholder categories filter": "Toutes les catégories",
        "placeholder allergies": "Allergies",
        "string order menu": "Commande",
        "string new customer": "client",
        "string multiple customers": "Plusieurs clients",
        "string total order": "Total",
        "string account balance order": "Solde du compte",
        "string balance after order": "Nouveau solde",
        "button info" : "i",
        "button fridge code": "Code",
        "button fridge code explanation": "maintenir to voir",
        "pop up order sent": "La commande a été envoyée a notre barman",
        "string drag order": "Glisser l'article ici pour commander",
        "message customer name": "Please input your name:",
        "navigation order": "COMMANDE",
        "navigation inventory": "INVENTAIRE",
        "button single order": "Commande unique",
        "button modify order": "Modifier commande",
        "button finished modify": "Fin de la modification",
        "button add from menu": "Ajouter depuis le menu",
        "button duplicate": "Dupliquer",
        "button discount": "Réduction",
        "button free": "Gratuit",
        "button remove": "Supprimer",
        "string unassigned": "Non attribué",
        "string add customer allcaps": "AJOUTER CLIENT",
        "string remove customer allcaps": "SUPPRIMER CLIENT"
    },

    indo : {
        "language": "Bahasa",
        "lang": "idn",
        "string welcome page": "Selamat datang di kapal kami",
        "button login": "Masuk",
        "button logout": "Keluar",
        "string swipe up": "Geser ke atas jika Anda tidak memiliki akun",
        "string sign in": "Masuk",
        "label email id": "Email id",
        "placeholder email": "me@email.com",
        "label password": "Kata Sandi",
        "button back": "Kembali",
        "pop up login out": "Anda telah berhasil keluar",
        "string table": "nomor meja", //need to reverse e.g. nomor meja 1
        "string balance": "saldo", //need to reverse e.g. saldo Olivia
        "string special VIP section": "Spesial untuk Anda",
        "placeholder search bar": "cari",
        "placeholder categories filter": "Semua Kategori",
        "placeholder allergies": "Alergi",
        "string order menu": "Pesan",
        "string new customer": "pelanggan",
        "string multiple customers": "Pelanggan Multipel",
        "string total order": "Total",
        "string account balance order": "Saldo Rekening",
        "string balance after order": "Saldo baru",
        "button info" : "i",
        "button fridge code": "Kode",
        "button fridge code explanation": "tekan untuk melihat",
        "pop up order sent": "Pesanan telah terkirim ke bartender kami",
        "string drag order": "Tarik item kesini untuk memesan",
        "message customer name": "Silakan masukkan nama Anda:",
        "navigation order": "PESAN",
        "navigation inventory": "INVENTARIS",
        "button single order": "Pesanan Tunggal",
        "button modify order": "Memodifikasi Pesanan",
        "button finished modify": "Selesai Memodifikasi",
        "button add from menu": "Tambahkan Dari Menu",
        "button duplicate": "Duplikat",
        "button discount": "Diskon",
        "button free": "Gratis",
        "button remove": "Hapus",
        "string unassigned": "Belum Itugaskan",
        "string add customer allcaps": "TAMBAHKAN PELANGGAN",
        "string remove customer allcaps": "HAPUS PELANGGAN"
    }
}